### ISSUE TITLE
Following release from 0.1.2 needs to be 0.2.1

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [ansys/ansys-api-pyensight#7]
Due to errors during release process, next release needs to be 0.2.1

**Comment by mariostieriansys** [comment]
@AlejandroFernandezLuces just created a new tag and release named 0.2.1 to include the dependency versions changes we discussed earlier

**Comment by AlejandroFernandezLuces** [comment]
Nice! Closing this issue
